version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - /root/docker/prometheus/data:/prometheus TODO 不能挂载外部目录，报错
    restart: on-failure
    privileged: true
    depends_on:
      - cadvisor
    ports:
      - 9090:9090
    networks:
      - cdp-network

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - NODE_ID={{.Node.ID}}
    cap_add:
      - SYS_TIME
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    networks:
      - cdp-network

  grafana:
    image: grafana/grafana:6.1.3
    container_name: grafana
    hostname: grafana
    volumes:
      - /root/docker/grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.server.name
      - GF_SECURITY_ADMIN_PASSWORD=local
      - GF_USERS_ALLOW_SIGN_UP='false'
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - cdp-network

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    hostname: cadvisor
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure
    privileged: true
    volumes:
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - cdp-network

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: on-failure
    ports:
      - 9093:9093
    networks:
      - cdp-network
    environment:
      - SLACK_URL=${SLACK_URL:-https://hooks.slack.com/services/TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-devops-alerts}
      - SLACK_USER=${SLACK_USER:-alertmanager}
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
#    volumes:
#      - /root/docker/alertmanager/data:/alertmanager
#      - /root/docker/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  unsee:
    container_name: unsee
    hostname: unsee
    image: cloudflare/unsee:v0.8.0
    restart: on-failure
    networks:
      - cdp-network
    environment:
      - TZ=Asia/Shanghai
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"

networks:
  cdp-network:
    external: true